//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeCapture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawyer_Task_Client
    {
        public int ID { get; set; }
        public int LayerID { get; set; }
        public int TaskID { get; set; }
        public int ClientID { get; set; }
        public int IsActive { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
